# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ccb483bc2ba2f17f948280a111946e1e848d25e2c856dd6fe9427b11cb5b4285a55fd2a48f55bd5818da293ec45d84d2a4ef7227f0890025b5f2972439af5e8

test:
  secret_key_base: e83e470d570dd159f1d4f69be6724e11a899d10d7627dd30ebb62d86e446cf72ff84745e8b95cf2a656c2aecda5f8213e299c78d993f2371c3ff3148e9ea6663

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
